## 网站名
title: 文蔺的博客

## 网站描述
description: 文蔺的前端学习记录，国外技术文章翻译，个人学习心得等等这些都会记录在这里。

## favicon 路径, /static 目录下的文件默认是根目录
favicon: /img/favicon.ico

## 网站作者
site_owner: 文蔺

## 网站域名
hostname: www.wemlion.com

## Twitter 或者 weibo 地址 
# twitter_url: https://twitter.com/

## github 地址
github_url: https://github.com/AngusFu/

## logo 图片路径
logo_url: /imgs/avatar.jpg

## gitalk config
## https://github.com/gitalk/gitalk
gitalk:
  clientID: be59313ed5e732f15480
  clientSecret: b682a90980bc35fa770b539d5f6bf0a7d400eb08
  repo: nuxt-firekylin
  owner: AngusFu
  admin: ['AngusFu']
  distractionFreeMode: false

## 左侧导航栏配置
navigation:
  -
    url: /
    option: home
    label: 主页
  - 
    url: /archives
    option: archive
    label: 归档
  - 
    url: /tags
    option: tags
    label: 标签
  -
    url: /about
    option: user
    label: 关于
  - 
    url: /link
    option: link
    label: 关注

  - url: /collection
    option: archive
    label: 收藏

## 分页大小
page_size: 10
